CREATE TABLE produtos (
  id BIGSERIAL PRIMARY KEY,
  codigo VARCHAR(255) NOT NULL UNIQUE,
  descricao VARCHAR(255) NOT NULL,
  saldo INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);